version: '3'

services: 
    mysqldb:
        image: mysql
        restart: always
        ports:
          - '3307:3306'
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=carro